// Generated by CoffeeScript 1.6.3
var Promise, QuickScrape, cheerio, config, qs, rp, _;

rp = require('request-promise');

Promise = require("bluebird");

cheerio = require('cheerio');

_ = require('lodash');

config = {
  'domain': 'http://www.judicialcollege.vic.edu.au',
  'url': 'http://www.judicialcollege.vic.edu.au/publications',
  'container': '#primary-navigation > ul > li.expanded.active-trail a[href]'
};

QuickScrape = (function() {
  function QuickScrape(config) {
    this.config = config != null ? config : {};
    this.jsPromise = rp(config.url).then(function(response) {
      var $, pubUrls;
      $ = cheerio.load(response);
      pubUrls = [];
      $(config.container).map(function(i, link) {
        var href;
        href = config.domain + $(link).attr('href');
        pubUrls.push(href);
      });
      return pubUrls;
    }).then(function(pubUrls) {
      var finalUrls;
      finalUrls = [];
      return Promise.map(pubUrls, function(pubUrl) {
        return rp(pubUrl).then(function(response) {
          var $, href, match, o, title;
          $ = cheerio.load(response);
          href = $('div.content > div.view-publication-link > a[href]').attr('href');
          title = $('div.content > div.publication-title').text();
          if (href == null) {
            return;
          }
          if (match = href.match(/eManuals\/([A-Za-z_]+)\/index.htm/)) {
            console.log('match', match[1]);
            finalUrls.push(match[1]);
            return o = {
              key: match[1],
              value: title.trim()
            };
          }
          return console.log('No match: ', href);
        });
      }).call("filter", function(href) {
        return (href != null ? href.key : void 0) != null;
      });
    }).then(function(pubUrls) {
      return console.log('Outer loop done', JSON.stringify(pubUrls));
    });
    console.log('promise', this.jsPromise);
  }

  return QuickScrape;

})();

qs = new QuickScrape(config);
